title: Neil Johari
email: neil@johari.tech
description: Staff Software Engineer at Roblox. University of Michigan alum.
baseurl: ""
url: "https://johari.tech"
github_username: neiljohari

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
